# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase Email Verification' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Email Verification
  pod 'Firebase'
  pod 'FirebaseAuth'

  target 'Firebase Email VerificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Firebase Email VerificationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
